on:
    push:
        branches: 
            - master





jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: "login to Docker"
            run: docker login --username ${{ secret.UserName }} --password ${{ secret.Token }}




