on:
    push:
        branches: 
            - master





jobs:
    build:
        runs-on: ubuntu-latest

        steps:
          - uses: actions/checkout@v3

          - name: "login to Docker"
            run: docker login --username ${{ secrets.UserName }} --password ${{ secrets.Token }}
       
          - name: "Building Docker image"  
             run: docker build -t ${{ secrets.UserName }}/myimage


          - name: "pushing to dockerHub"
             run: docker push ${{ secrets.UserName }}/myimage
